name: bar_chart_race
description: A library to draw fantastic bar charts race in Flutter.
version: 0.0.1
homepage: https://github.com/younes38/bar_chart_race

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
